pipeline{
    agent any
    stages{
        stage("Build"){
            steps{
             echo "This is a build stage"
            }
        }
        stage("Test"){
            steps{
             echo "This is a Test stage"
            }
        }
        stage("Deploy"){
             steps{
                echo "This is a deploy stage"
            }
        }
    }
}